HumanTrackingSystem/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   path('admin/', admin.site.urls),
    path('', include('accountManagement.urls')),
    path('statistics/', include('statisticsManagement.urls')),
    path('system/', include('systemManagement.urls')),
    path('securityManagement/', include('securityManagement.urls')),
    path('prediction/',include('prediction.urls')),
]

prediction/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Analysis, name='Prediction'),
    path('getPre/', views.getPre, name='getPre'),
]

statisticsManagement/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('dailyRecord', views.DailyRecords, name = 'DailyRecords'),
    path('timelyRecord', views.TimelyRecords, name = 'TimelyRecords')
]

statisticsManagement/models.py
from django.db import models

from django.utils.translation import gettext_lazy as _

class TimelyRecord(models.Model):

    record_date = models.DateField(
        _('Record Date'),
    )

    record_time = models.TimeField(
        _('Record Time'),
    )

    record_count = models.IntegerField(
        _('Count of people'),
    )

    @classmethod
    def getRecordsOnDate(cls, date):
        return cls.objects.filter(record_date__exact = date)

class DailyRecord(models.Model):

    record_date = models.DateField(
        _('Record date'),
    )

    total_count = models.IntegerField(
        _('Record count'),
    )

    peak_hour_start = models.TimeField(
        _('Start of Peak hour'),
    )

    peak_hour_end = models.TimeField(
        _('End of Peak hour'),
    )

    @classmethod
    def fetchWithinRange(cls, start_date, end_date):
        if start_date < end_date:
            return cls.objects.filter(record_date__range = (start_date, end_date))

    @classmethod
    def findPeakWithinRange(cls, start_date, end_date):
        if start_date < end_date:
            result = cls.objects.filter(record_date__range = (start_date, end_date))
            peakValue = result.aggregate(models.Max('total_count'))['total_count__max']
            return result.filter(total_count = peakValue)

statisticsManagement/forms.py
from django import forms

from django.utils import timezone

from datetime import timedelta

class DateInput(forms.DateInput):
    input_type = 'date'

class DateRangeSearchForm(forms.Form):
    maxEndDate = (timezone.localtime().today() - timedelta(days = 1)).date()
    maxStartDate = (timezone.localtime().today() - timedelta(days = 2)).date()
    start_date = forms.DateField(
        initial = (timezone.localtime().today() - timedelta(days = 15)).date(),
        widget = DateInput(attrs = {"max" : maxStartDate.isoformat, 'class' : 'form-control'}),
    )

    end_date = forms.DateField(
        initial = maxEndDate,
        widget = DateInput(attrs = {"max" : maxEndDate.isoformat, 'class' : 'form-control'}),
    )

    today = timezone.localtime().today().date()
    

    auto_adjust = forms.BooleanField(
        required = False,
        widget = forms.CheckboxInput,
        initial = True,
    )


class DateForm(forms.Form):
    
    today = timezone.localtime().today().date()
    single_date = forms.DateField(
        widget = DateInput(attrs = {"max" : today.isoformat, 'class' : 'form-control'}),
        initial = today,
    )

    auto_adjust = forms.BooleanField(
        required = False,
        widget = forms.CheckboxInput,
        initial = True,
    )

statisticsManagement/controllers.py
from .models import DailyRecord, TimelyRecord
from accountManagement.models import User

import os.path
from reportlab.platypus import SimpleDocTemplate, Spacer, Paragraph, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.lineplots import LinePlot
from reportlab.graphics.widgets.markers import makeMarker

from django.utils import timezone
import datetime
import calendar

import random

'''
from statisticsManagement.controllers import sendMonthlyReport
sendMonthlyReport()
'''

def createChart(records, peakValue):
    data = [[]]
    for r in records:
        data[0].append((r.record_date.day, r.total_count))

    chart = LinePlot()
    chart.data = data
    chart.x, chart.y = 5, 5
    chart.height, chart.width = 200, 400

    chart.xValueAxis.valueMin = 1
    chart.xValueAxis.valueStep = 1
    chart.yValueAxis.valueMin = 0
    chart.yValueAxis.valueMax = (peakValue//10)*10 + 10
    chart.yValueAxis.valueStep = 10

    chart.lines[0].symbol = makeMarker('Circle')
    chart.lineLabelFormat = "%d"

    drawing = Drawing()
    drawing.add(chart) 

    return drawing

def createTable(records):
    data = [
        ["Date", "Total Count", "Peak Hour"],
    ]

    for r in records:
        date = r.record_date.strftime("%Y-%m-%d")
        peakHour = "%s to %s"%(r.peak_hour_start.strftime("%H:%M"),r.peak_hour_end.strftime("%H:%M"))
        data.append([date, r.total_count, peakHour])

    table = Table(data, colWidths=(1.5*inch, inch, 2*inch))

    style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('ALIGN', (0,0), (-1,-1), 'CENTRE')
    ])
    table.setStyle(style)

    return table

"""
returns a PDF containing a graph and a list of statistics for the given month of firstDay
returns None if no data is available for that month
"""
def createPDF(firstDay):
    lastDay = firstDay.replace(day=calendar.monthrange(firstDay.year, firstDay.month)[1])
    records = DailyRecord.fetchWithinRange(firstDay, lastDay)

    if records:
        folder = os.path.join("statisticsManagement", "monthly_reports")
        filename = os.path.join(folder, "HTS_Monthly_Report_%s.pdf"%(firstDay.strftime("%B_%Y")))
        pdf = SimpleDocTemplate(
            filename=filename,
            pagesize=letter,
            rightmargin=72, leftmargin=72, topmargin=72, bottommargin=72
        )

        contents = []
        styles = getSampleStyleSheet()

        title1 = Paragraph("Monthly Report - %s"%(firstDay.strftime("%B, %Y")), styles['Heading1'])
        title2 = Paragraph("Counting Statistics", styles['Heading2'])

        contents.append(title1)
        contents.append(title2)
        noteString = Paragraph("This is a system-generated document.", styles['Normal'])
        contents.append(noteString)
        contents.append(Spacer(1, inch))

        peakDays = DailyRecord.findPeakWithinRange(firstDay, lastDay)
        peakValue = peakDays[0].total_count

        chart = createChart(records, peakValue)

        contents.append(chart)

        contents.append(Spacer(1, inch))

        peakTitleString = "Peak Day" if len(peakDays) == 1 else "Peak Days"
        peakTitleString += "\t(Total Count = %d) :"%(peakValue)
        peakTitle = Paragraph(peakTitleString, styles['Heading3'])

        contents.append(peakTitle)

        for day in peakDays:
            dayString = day.record_date.strftime("%Y-%m-%d")
            peakDay = Paragraph(dayString, styles['Normal'])
            contents.append(peakDay)

        contents.append(PageBreak())

        styles['Heading4'].alignment = 1
        listViewTitle = Paragraph("Daily records in detail", styles['Heading4'])
        contents.append(listViewTitle)
        contents.append(Spacer(1, 0.25*inch))

        table = createTable(records)
        contents.append(table)

        pdf.build(contents)
        return filename
    else: return None

"""
Returns 1 if sent to all recipients, 0 if sending failed, -1 if no data available
That way, we can be sure that no empty reports are sent.
"""
def sendMonthlyReport():
    today = datetime.datetime.today()
    firstDayOfPastMonth = datetime.date(today.year, today.month - 1, 1)
    pdf = [createPDF(firstDayOfPastMonth)]

    if pdf:
        recpients = User.objects.filter(receive_reports = True)
        month = firstDayOfPastMonth.strftime("%B, %Y")
        subject = "Monthly Report - %s"%(month)
        message = ("Please find the attached PDF document containing Counting statistics of %s"%(month))

        sentStatus = 1
        for r in recpients:
            sent = r.email_user_with_attachments(subject, message, pdf)
            if not sent: 
                sentStatus = 0

        return sentStatus
    else: return -1

'''
params: date = 3-tuple (YYYY, MM, DD)
'''
def save_all_timely_records(date):
    timelyCounts = {}
    startTime = datetime.datetime(date[0], date[1], date[2], 0, 0)
    for t in range(48):
        time = startTime + datetime.timedelta(minutes = 30*t)
        h = time.hour
        count = 0
        if h >= 8 and h < 12:
            count = random.randint(1, 5)
        elif h >= 12 and h < 17:
            count = random.randint(1, 10)
        elif h >= 17 and h < 20:
            count = random.randint(1, 5)
        timelyCounts[time.strftime("%H:%M:%S")] = count
    
    maxCount = 0
    timeStamps = list(timelyCounts.keys())
    totalCount = timelyCounts[timeStamps[0]]

    for t in range(len(timeStamps) - 1):
        hourlyCount = timelyCounts[timeStamps[t]] + timelyCounts[timeStamps[t + 1]]
        if hourlyCount >= maxCount: 
            maxCount = hourlyCount
            peakHourStart = datetime.time.fromisoformat(timeStamps[t])
        totalCount += timelyCounts[timeStamps[t + 1]]

    # a dummy date is required because timedelta operations can be done only with datetime objects
    dummyDate = datetime.datetime(100, 1, 1, peakHourStart.hour, peakHourStart.minute)

    # adjustments to properly represent the peak hour
    peakHourStart = (dummyDate - datetime.timedelta(minutes=30)).time()
    peakHourEnd = (dummyDate + datetime.timedelta(minutes=30)).time()

    record_string = ""
    for k in list(timelyCounts.keys()):
        record_string += "%s,%s,%d"%(startTime.strftime("%Y-%m-%d"), k, timelyCounts[k]) + "\n"

    return str(totalCount), peakHourStart.strftime("%H:%M:%S"), peakHourEnd.strftime("%H:%M:%S"), record_string

def save_all_records(startDate, endDate):
    start_date = datetime.datetime(startDate[0], startDate[1], startDate[2], 0, 0)
    end_date = datetime.datetime(endDate[0], endDate[1], endDate[2], 0, 0)

    timely_string = ""
    daily_string = ""

    date = start_date
    while date <= end_date:
        record = save_all_timely_records((date.year, date.month, date.day))
        timely_string += record[3]
        daily_record = "%s,%s,%s,%s"%(date.strftime("%Y-%m-%d"), record[0], record[1], record[2])
        daily_string += daily_record + "\n"
        
        date = date + datetime.timedelta(days=1)

    folder = os.path.join("statisticsManagement", "dummy_data")
    timely_filename = os.path.join(folder, "%s to %s timely.txt"%
    (start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d")))
    daily_filename = os.path.join(folder, "%s to %s daily.txt"%
    (start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d")))

    t = open(timely_filename, "w")
    t.write(timely_string.strip())
    t.close()

    d = open(daily_filename, "w")
    d.write(daily_string.strip())
    d.close()

def saveAllToDatabase(timely_filename = None, daily_filename = None):
    folder = os.path.join("statisticsManagement", "dummy_data")
    if timely_filename:
        timely_filename = os.path.join(folder, timely_filename)
        t = open(timely_filename, "r")
        t_lines = t.readlines()
        t.close()
        for line in t_lines:
            if line != '':
                content = line.strip().split(',')
                rec_date = datetime.date.fromisoformat(content[0])
                rec_time = datetime.time.fromisoformat(content[1])
                rec_count = int(content[2])
                record = TimelyRecord(record_date = rec_date, 
                record_time = rec_time, record_count = rec_count)
                record.save()
                print(record)
    if daily_filename:
        daily_filename = os.path.join(folder, daily_filename)
        d = open(daily_filename, "r")
        d_lines = d.readlines()
        d.close()
        for line in d_lines:
            if line != '':
                content = line.strip().split(',')
                rec_date = datetime.date.fromisoformat(content[0])
                rec_count = int(content[1])
                peak_start = datetime.time.fromisoformat(content[2])
                peak_end = datetime.time.fromisoformat(content[3])
                record = DailyRecord(record_date = rec_date, total_count = rec_count, 
                peak_hour_start = peak_start, peak_hour_end = peak_end)
                record.save()
                print(record.total_count)

'''
from statisticsManagement.controllers import save_all_records, saveAllToDatabase
save_all_records((2020,4,1), (2020,4,30))
saveAllToDatabase(timely_filename = "")
'''

statisticsManagement/templates/statisticsManagement/DailyRecordChart.html
{% extends 'mainbase.html' %}
{% load static %}
{% block title %}Statistics - Date Range{% endblock %}
{% block content %}
<style>
    /* html,
   
    html,body{
        /* background-image: url('{%static "background/Brick wall background.png" %}'); */
        background-size: cover;
        background-repeat: no-repeat;
        height: 100%;
        font-family: 'Numans', sans-serif;
    }
</style>

<div class="col" style="background-color: rgba(255,255,255,0.5); padding-bottom: 2vw;">
    <h1 class="display-4 text-center">Records within a range of dates</h1>
    <form action="{% url 'DailyRecords' %}" method="POST">
        {% csrf_token %}

        <div class="row" style="margin-left: 20%; margin-right: 20%;">
            <div class="col-md-5"><label for="id_start_date"><h3>Start Date: </h3></label> {{ form.start_date }}</div>
            <div class="col-md-5"><label for="id_start_date"><h3>End Date: </h3></label> {{ form.end_date }}</div>
            <div id="search_panel" class="col-md-2">
                <input type="submit" value="Search" class="col btn btn-primary" style="margin-top: 2vw;" id="search">
            </div>
        </div>


    </form>
    {% if all_results %}
    <div style="margin-left: 10%; margin-right: 5%; ">
        <div class="row">
        <div class="chartWrapper">
    <div class="chartAreaWrapper">
        <div class="chartAreaWrapper2">
          <canvas id="myChart" height="500" width="1200"></canvas>
        </div>
     </div>
    
    </div>
            
                <script>

                    const label = [{%for i in all_results %}'{{i.record_date}}', {% endfor %}];
                    const data = [{%for i in all_results %}'{{i.total_count}}', {% endfor %}]


                    var rectangleSet = true;
                    var ctx = document.getElementById('myChart').getContext('2d');
                    var myChart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: label,
                            datasets: [{
                                label: 'count',
                                data: data,

                                backgroundColor: 
                                    '#1a237e ',

                                borderWidth: 4,
                                fill: false,
                                lineTension: 0
                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        fontColor: "black",
                                        fontSize: 10,
                                        beginAtZero: true
                                    },
                                    scaleLabel: {
                                        display: true,
                                        labelString: 'Count',
                                        fontColor: "black",
                                        fontSize: 20,
                                    },
                                }],
                                xAxes: [{
                                    ticks: {
                                        fontColor: "black",
                                        fontSize: 10,

                                        beginAtZero: true
                                    },
                                    scaleLabel: {
                                        display: true,
                                        labelString: 'Date',
                                        fontColor: "black",
                                        fontSize: 20,
                                    },
                                }]
                            }
                        },
                      
                        
                    });
                </script>
            </div>
        </div>

        <div class="row" style="margin-top:2vw ;margin-left: 20%; margin-right: 20%;">
      
            <p style="font-size: x-large;">
                <span style="color: red; margin-top: 1vw;">Peak day{{ peak_results|pluralize }}: </span>
                {% for each in peak_results %}
                <span>{{ each.record_date|date:"Y-m-d"}} (Total Count = {{ each.total_count }})</span>
                {% endfor %}
            </p>
        </div>


        <div class="row" style="margin-top:2vw ;margin-left: 10%; margin-right: 10%;">
            <table class="table table-borderless table-hover " style="margin-top: 5vw; text-align: center; table-layout: fixed;">
                <tr style="background-color:rgba(0,64,112); color:white;">
                    <th>Date</th>
                <th>Total Count</th>
                <th>Peak hour</th>
                </tr>
                

                {% for each in all_results %}
                <tr {% if each in peak_results %} style="background-color: palevioletred;" {% endif %}
                    {% if each.record_date == single_date %} style="background-color: greenyellow;" {% endif %}></tr>
                <td style="padding-left: 5px;">{{ each.record_date|date:"Y-m-d" }}</td>
                <td>{{ each.total_count }}</td>
                <td>{{ each.peak_hour_start|date:"H:i" }} to
                    {{ each.peak_hour_end|date:"H:i" }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% elif invalid_date_range %}
    <div style="color: red; margin-top: 5%;" class="text-center"><h4>Invalid Date Range!</h4></div>
    {% else %}
    <div class="text-center" style="margin-top: 5%;">
        <h4>Sorry, No Results!</h4>
    </div>
    {% endif %}
</div>

{% endblock %}

statisticsManagement/templates/statisticsManagement/TimelyRecordChart.html
{% extends 'mainbase.html' %}

{% block title %}Statistics - Date{% endblock %}
{% block content %}

<div class="col" style="background-color: rgba(255,255,255,0.5); padding-bottom: 2vw;">
    <h4 class="display-4 text-center">Records on a given date</h4>
    <form action="{% url 'TimelyRecords' %}" method="POST">
        {% csrf_token %}
        <div class="row" style="margin-left: 25vw;">
            <div class="col-md-3" style="margin-left: 8%;" title="Date to show the time-based counts. Latest date should be today"><label for="id_single_date">Date: </label>
                {{ form.single_date }}</div>
            <div class="col-md-3">
                <input type="submit" value="Search" class="col btn btn-primary" style="margin-top: 1.5vw;" id="search">
            </div>
        </div>

    </form>
    {% if single_date_timely_results %}
    <div style="margin-left: 10%; margin-right: 5%;">
        <div class="row">
           <div class="chartWrapper">
    <div class="chartAreaWrapper">
        <div class="chartAreaWrapper2">
          <canvas id="Chart" height="500" width="1200"></canvas>
        </div>
     </div>
    
    </div>
            
                <script>

                    const label = [{%for i in single_date_timely_results %}'{{i.record_time}}', {% endfor %}];
                    const data = [{%for i in single_date_timely_results %}'{{i.record_count}}', {% endfor %}]




                    var ctx = document.getElementById('Chart').getContext('2d');
                    var Chart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: label,
                            datasets: [{
                                label: 'count',
                                data: data,
                                backgroundColor:'#1a237e ',
                                borderWidth: 4,
                                fill: false,
                                lineTension: 0
                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        fontColor: "black",
                                        fontSize: 10,
                                        beginAtZero: true
                                        
                                    },
                                    scaleLabel: {
                                        display: true,
                                        labelString: 'Count',
                                        fontColor: "black",
                                        fontSize: 15,
                                    },
                                }],
                                xAxes: [{
                                    ticks: {
                                        fontColor: "black",
                                        fontSize: 10,
                                        beginAtZero: true
                                    },
                                    scaleLabel: {
                                        display: true,
                                        labelString: 'Time',
                                        fontColor: "black",
                                        fontSize: 15,
                                    },
                                }]
                            }
                        }
                    });
                </script>
            </div>
        </div>
        <div class="row text-center" style="font-size: x-large; margin-top:2vw;">
            {% if single_date_daily_result %}
            <div class="col-md-6"><span style="color: red;">Total Count = </span>{{ single_date_daily_result.total_count }}</div>
            <div class="col-md-6"><span style="color: red;">Peak hour = </span>
                {{ single_date_daily_result.peak_hour_start|date:"H:i"}}
                to
                {{ single_date_daily_result.peak_hour_end|date:"H:i"}}</div>
            {% endif %}
        </div>

        <div class="row" style="margin-top:2vw ;margin-left: 10%; margin-right: 10%;">
            <table class="table table-borderless table-hover table-striped" style="margin-top: 5vw; text-align: center; table-layout: fixed;">
            <tr style="background-color:rgba(0,64,112); color:white;">
                <th>Time</th>
                <th>Count</th>
                </tr>
                

                {% for each in single_date_timely_results %}
                <tr {% if each.record_time in single_date_peak_times %} style="background-color:palevioletred;"
                    {% endif %}>
                    <td>{{ each.record_time }}</td>
                    <td>{{ each.record_count }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% else %}
    <div class="text-center" style="margin-top: 10%;">
        <h4>Sorry, No Results!</h4>
    </div>

    {% endif %}
</div>
{% endblock %}

statisticsManagement/templates/statisticsManagement/sendMonthlyReport.html
{% extends 'mainbase.html'%}

{% block title %}Send Monthly Report{% endblock %}

{% block content %}

<div class="col">
    <h1 class="display-4">Send Monthly Report of {{ prevMonth }}</h1>
{% if not success %}
    {% if connectivity %}
    <form action="{% url 'send_monthly_report' %}" method="POST">
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
    {% else %}
    <h1 class="display-3" style="color: red;">No Internet!</h1>
    <h3>Internet connection is necessary to send monthly reports.</h3>
    <h3>Please connect your device to the internet, and then refresh the browser.</h3>
    {% endif %}
{% else %}
    {% if nodata %}
        <h3 style="color: green">There is no data available for {{ prevMonth }}</h3>
    {% else %}
        <h3 style="color: green">Successfully Sent!</h3>
    {% endif %}
{% endif %}

</div>

{% endblock %}

statisticsManagement/templates/statisticsManagement/viewDailyRecords.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Records</title>

</head>

<body>


    <form action="{% url 'daily_records' %}" method="POST">
        {% csrf_token %}
        <table style="width: 100%;">
            <thead>
                <tr>
                    <th>
                        <h1>Records within a range of dates</h1>
                        <label for="id_start_date">Start Date: </label> {{ form.start_date }}
                        <label for="id_start_date">End Date: </label> {{ form.end_date }}
                    </th>
                    <th>
                        <h1>Records on a given date</h1>
                        <label for="id_single_date">Date: </label> {{ form.single_date }}
                    </th>
                    <th>
                        {{ form.auto_adjust }}
                        <label for="id_auto_adjust">Auto Adjust Date range to contain selected date</label>
                        <br>
                        <input type="submit" value="Search">
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="display:block;">
                        {% if all_results %}
                        <table style="width: 90%;">
                            <th align="center">Date</th>
                            <th align="center">Total Count</th>
                            <th align="center">Peak hour</th>

                            {% for each in all_results %}
                            <tr {% if each in peak_results %} style="background-color: palevioletred;" {% endif %}
                                {% if each.record_date == single_date %} style="background-color: greenyellow;"
                                {% endif %}>
                                <td align="center">{{ each.record_date|date:"Y-m-d" }}</td>
                                <td align="center">{{ each.total_count }}</td>
                                <td align="center">{{ each.peak_hour_start|date:"H:i" }} to
                                    {{ each.peak_hour_end|date:"H:i" }}</td>
                            </tr>
                            {% endfor %}
                        </table>

                        <h3 style="color: red;">Peak day{{ peak_results|pluralize }}: </h3>
                        {% for each in peak_results %}
                        <p>{{ each.record_date|date:"Y-m-d"}} (Total Count = {{ each.total_count }})</p>
                        {% endfor %}

                        {% elif invalid_date_range %}
                        <p style="color: red;">Invalid Date Range!</p>
                        {% else %}
                        <p>Sorry, No Results </p>
                        {% endif %}
                    </td>
                    <td>
                        {% if single_date_timely_results %}
                        <table style="width: 90%;">
                            <th align="center">Time</th>
                            <th align="center">Count</th>

                            {% for each in single_date_timely_results %}
                            <tr {% if each.record_time in single_date_peak_times %}
                                style="background-color:palevioletred;" {% endif %}>
                                <td align="center">{{ each.record_time|date:"H:i" }}</td>
                                <td align="center">{{ each.record_count }}</td>
                            </tr>
                            {% endfor %}
                        </table>
                        {% endif %}

                        {% if single_date_daily_result %}
                        <p>Total Count = {{ single_date_daily_result.total_count }}</p>
                        <p>Peak hour =
                            {{ single_date_peak_times|first|date:"H:i"}}
                            to
                            {{ single_date_peak_times|last|date:"H:i"}}</p>

                        {% endif %}
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </form>

</body>

</html>