HumanTrackingSystem/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   path('admin/', admin.site.urls),
    path('', include('accountManagement.urls')),
    path('statistics/', include('statisticsManagement.urls')),
    path('system/', include('systemManagement.urls')),
    path('securityManagement/', include('securityManagement.urls')),
    path('prediction/',include('prediction.urls')),
]

prediction/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Analysis, name='Prediction'),
    path('getPre/', views.getPre, name='getPre'),
]

securityManagement/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Security, name='Security'),
    path('recipientadd/', views.RecipientAdd, name='RecipientAdd'),
    path('recipientremove/<str:pk>/', views.RecipientRemove, name='RecipientRemove'),
    path('recipientedit/<str:pk>/', views.RecipientEdit, name='RecipientEdit'),
    # path('alert/', views.alert, name = 'alert'),
    
]

securityManagement/models.py
from django.db import models

class Recipient(models.Model):
   
    register_num = models.IntegerField(unique = True)

    name = models.CharField(max_length=200)
    
    email = models.EmailField(
        max_length=200,
        unique = True,
        error_messages = {
            'unique': "The email is already being used by a recipient.",
        },
    )

# Create your models here.

securityManagement/forms.py
from django import forms

from .models import Recipient

class RecipientAddForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields= ['register_num', 'name', 'email']

        widgets = {
            'register_num' : forms.NumberInput(attrs={'class' : 'form-control'}),
            'name' : forms.TextInput(attrs={'class' : 'form-control'}),
            'email' : forms.EmailInput(attrs={'class' : 'form-control'}),
        }

securityManagement/controllers.py
import datetime

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect

from .models import Recipient

def send_security_alert():
    all_recipients = Recipient.objects.values_list('email')

    date = datetime.datetime.today().strftime("%Y-%m-%d")
    time = datetime.datetime.now().time().strftime("%H:%M:%S")

    try:
        for email in all_recipients:
            send_mail(
            'Securiy Alert from HTS', #subject
            'Human Detected on %s at %s'%(date, time), #message
            settings.EMAIL_HOST_USER, #from
            email, #to
            fail_silently = False
            )
        return True
    except:
        return False

securityManagement/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.decorators import user_passes_test

from django.http import HttpResponse

from accountManagement.controllers import checkIsAdmin
from .models import Recipient
from .forms import RecipientAddForm

@user_passes_test(checkIsAdmin, login_url='index')
def Security(request):
    recipients = Recipient.objects.all()
    return render(request,'security.html', {'Recipient':recipients} )

@user_passes_test(checkIsAdmin, login_url='index')
def RecipientAdd(request):
    form = RecipientAddForm()
    
    if request.method == 'POST':
        form = RecipientAddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/securityManagement')
       
    return render (request, 'recipientAdd.html',{'form':form})



@user_passes_test(checkIsAdmin, login_url='index')
def RecipientRemove(request,pk):
    recipient = Recipient.objects.get(id = pk)
    if request.method=="POST":
        recipient.delete()
        return redirect('/securityManagement')
    context = {'item' : recipient}
    return render(request, 'recipientRemove.html', context)



@user_passes_test(checkIsAdmin, login_url='index') 
def RecipientEdit(request,pk):
    recipient = Recipient.objects.get(id=pk)
    form = RecipientAddForm(instance=recipient)

    if request.method == 'POST':
        form = RecipientAddForm(request.POST , instance=recipient)
        if form.is_valid():
            form.save()
            return redirect('/securityManagement')
       
    
    return render (request, 'recipientAdd.html',{'form':form})

# def alert(request):
#     return render(request, 'alert.html')

securityManagement/templates/alert.html
{% extends 'mainbase.html' %}

{% block title %}ALERT{% endblock %}

{% block content %}
<style>
    html,body{
        background-color:#fffdfb;
    }
</style>
<div class="text-center" style="margin-top:25vw; margin-left: 8vw;">
    <h1 id="alertMessage" class="display-1 text-danger">ALERT!!!</h1>
</div>

{% endblock %}

securityManagement/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email</title>
</head>
<body>
    <p>There is a security aleart</p>
</body>
</html>

securityManagement/templates/recipientAdd.html
{% extends 'mainbase.html' %}

{% block title %}Add Recipient{% endblock %}

{% block content %}
<style>
    .card{
        height: 300px;
        margin-top: auto;
        margin-bottom: auto;
        width: 500px;
        background-color: rgba(255, 255, 255, 0.7) !important;
        }
    .square-1 {
        top: 10%;
        left: 6%;
    }
    .main_div { 
        text-align:center; 
        position: relative; 
        top: 100px;
        height: 50px; 
        width: 200px; 
    } 
</style>
<div class="main_div"><a type="button" class="btn btn-link text-default" href="{% url 'user_settings' %}">Back</a></div>

<div class="container">

    <div class="d-flex justify-content-center h-400">
        <div class="card card-cascade narrower" ">
            <div class="card-header">
                <h1 class="display-5 text-center">Security Alert Recipient</h1>
            </div>
            <div class="card-body text-dark">
            <form action="" method=POST>
                {% csrf_token %}

                <div class="form-group row ">
                    <div class="col-md-4 text-center">
                        <label for="id_register_num">Registration Number</label>
                    </div>
                    <div class="col-md-8">
                        {{ form.register_num }}
                        
                    </div>
                    {% if form.register_num.errors %}
                        <p class="col" style="color: red;">Registration number is not unique.</p>
                    {% endif %}
                </div>
                    <div class="form-group row">
                        <div class="col-md-4 text-center">
                            <label for="id_name" >Name</label>
                        </div>
                        <div class="col-md-8">
                            {{ form.name }}
                        </div>
                        
                    </div>
                
                    <div class=" form-group row">
                        <div class="col-md-4 text-center">
                            <label for="id_email">Email</label>
                        </div>
                        <div class="col-md-8">
                            {{ form.email }}
                        </div>
                        
                    </div>

                    <!-- <div class="col-md-6">
                        {{ form.name }}
                        <label for="id_name">Name</label>
                        {{ form.email }}
                        <label for="id_email">Email</label>
                    </div> -->
                    {% if form.email.errors %}
                    <p class="col" style="color: red;">Email is already being used by a recipient.</p>
                    {% endif %}
                
                <div style="margin-left: 40%;">
                    <input type="submit" name="register" value="Register" class="btn btn-primary ">
                </div>
                
            </form>
        </div>
    </div>
        </div>
    </div>
</div>
{% endblock %}

securityManagement/templates/recipientRemove.html
{% extends 'mainbase.html' %}

{% block title %}Remove Recipient{% endblock %}

{% block content %}
<style>
    html,body {
        background-color: #f8f4ef;
    }
</style>
<div class="col-md-6" style="margin-top:8vw; margin-left: 10vw;">
    <!-- <h1 class="display-4">Remove Recipient</h1> -->
    <h3 class="text-bold">Are you sure you want to delete "{{item.name}}"?</h3>

    <form action="{% url 'RecipientRemove' item.id %}" method=POST>

        {% csrf_token %}
        <a href="{% url 'Security' %}"><span class="btn btn-secondary" id="cancel">Cancel</span></a>

        <input type="submit" name="Confirm" value="Remove" class="btn btn-danger" id="remove">

    </form>
</div>
{% endblock %}

securityManagement/templates/security.html
{% extends 'mainbase.html' %}

{% block title %}Security{% endblock %}

{% block content %}
<style>
    html,
    body {
        background-color: #fffdfb;
    }

    .main_div { 
        text-align:center; 
        position: relative; 
        top: 10px;
        height: 50px; 
        width: 200px; 
        } 
</style>
<div class="main_div"><a type="button" class="btn btn-link text-default" href="{% url 'user_settings' %}">Back</a></div>
<!-- <div class="container-fluid"> -->
<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <h1 class="text-center display-4">Recipients of Security Alerts</h1>

            <div style="margin-bottom: 2vw;"></div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <table class="table table-borderless table-hover table-striped">
                        <tr style="background-color:rgba(0,64,112); color:white;">
                            <th>Reg. Number</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th></th>
                            <th></th>
                        </tr>
                        {%for i in Recipient%}
                        <tr>
                            <td>{{i.register_num}}</td>
                            <td>{{i.name}}</td>
                            <td>{{i.email}}</td>
                            <td><button class="btn btn-success"><a href="{% url 'RecipientEdit' i.id %}"
                                        class="text-white" style="text-decoration: none">Edit</a></button></td>
                            <td><button class="btn-danger btn"><a href="{% url 'RecipientRemove' i.id %}"
                                        class="text-white" style="text-decoration: none">Delete</a></button></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}